### ISSUE TITLE
Issue running under docker

### ISSUE THREAD

**Issue by matthewford** [uktrade/dit-clamav-rest#31]
Hi, 

I had to update my docker-compose config to the following for the tests to pass:

```
  clamd:
    image: gcr.io/sre-docker-registry/github.com/uktrade/docker-clamav:master
    user: root  # Run as root user
    volumes:
      - clamdb:/var/lib/clamav
      - /var/run/clamav:/var/run/clamav  # Ensure the socket directory is mounted
    environment:
      - MIRROR_URL=db.local.clamav.net
    command: /bin/sh -c "mkdir -p /var/run/clamav && chown clamav:clamav /var/run/clamav && freshclam && clamd"  # Ensure correct permissions and start clamd

```
